version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
         - 2345:5432
  app:
    build: .
    ports:
      - 4000:4000
    environment:
      PORT: 4000

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
